### ISSUE TITLE
doesn't work in github

### ISSUE THREAD

**Issue by markmark1** [quackduck/cool#1]
![Screen Shot 2021-08-11 at 7 07 50 PM](https://user-images.githubusercontent.com/6416539/129127579-082ddb5d-c6f4-4da7-8b82-4acecd58af46.jpg)
doesn't work in m1

**Comment by quackduck** [comment]
That is a known issue I believe I have documented?

**Comment by quackduck** [comment]
Ooh, turns out I have not documented this.

Thanks for bringing this to my attention!

I'm really sorry, Apple changed some very low level APIs and so M1s don't work :(
